name: Alpha Release

on:
  push:
    branches:
      - changeset-release/main
  pull_request:

jobs:
  release:
    if: github.head_ref == 'changeset-release/main' && github.ref == 'refs/head/main'
    name: Publish Alpha Version
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.23.1

      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Enter Pre-release Mode
        run: pnpm changeset pre enter alpha

      - name: Create release PR or publish to npm
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm release | tee output.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tags
        run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Post version to PR'
        uses: EliLillyCo/github-actions-post-to-pr@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          post_to_pr_definition: |
            [
              {
                "message_file": "./output.txt",
                "title": "Published Alpha"
              }
            ]
